import * as PAGE from '../pages/admin'
import * as ROUTES from '../constants/routes';

export const privateRoute = [
    {
        path:ROUTES.ADMIN_DASHBOARD,
        exact:true,
        component:PAGE.Dashboard
    },
    {
        path:ROUTES.ADMIN_PRODUCTS,
        exact:true,
        component:PAGE.ProductAdmin
    },
    {
        path:ROUTES.ADMIN_PRODUCTS_CREATE,
        exact:true,
        component:PAGE.ProductCreate
    },
    {
        path:ROUTES.ADMIN_PRODUCTS_EDIT,
        exact:true,
        component:PAGE.ProductEdit
    },
    {
        path:ROUTES.ADMIN_PRODUCTS_SHOW,
        exact:true,
        component:PAGE.ProductShow
    },
    {
        path:ROUTES.ADMIN_IMPORT_PRODUCT,
        exact:true,
        component:PAGE.Import
    },
    {
        path:ROUTES.ADMIN_IMPORT_PRODUCT_CREATE,
        exact:true,
        component:PAGE.ImportCreate
    },
    {
        path:ROUTES.ADMIN_CATEGORIES,
        exact:true,
        component:PAGE.Category
    },
    {
        path:ROUTES.ADMIN_CATEGORIES_CREATE,
        exact:true,
        component:PAGE.CategoryCreate
    },
    {
        path:ROUTES.ADMIN_CATEGORIES_EDIT,
        exact:true,
        component:PAGE.CategoryEdit
    },
    {
        path:ROUTES.ADMIN_CATEGORIES_SHOW,
        exact:true,
        component:PAGE.CategoryShow
    },
    {
        path:ROUTES.ADMIN_BRANDS,
        exact:true,
        component:PAGE.BrandAdmin
    },
    {
        path:ROUTES.ADMIN_BRANDS_CREATE,
        exact:true,
        component:PAGE.BrandCreate
    },
    {
        path:ROUTES.ADMIN_BRANDS_EDIT,
        exact:true,
        component:PAGE.BrandEdit
    },
    {
        path:ROUTES.ADMIN_BRANDS_SHOW,
        exact:true,
        component:PAGE.BrandShow
    },
    {
        path:ROUTES.ADMIN_MENUS,
        exact:true,
        component:PAGE.MenuAdmin
    },
    {
        path:ROUTES.ADMIN_ORDERS,
        exact:true,
        component:PAGE.OrderAdmin
    },
    {
        path:ROUTES.ADMIN_PAGES,
        exact:true,
        component:PAGE.PageAdmin
    },
    {
        path:ROUTES.ADMIN_PAGES_CREATE,
        exact:true,
        component:PAGE.PageCreate
    },
    {
        path:ROUTES.ADMIN_MENUS,
        exact:true,
        component:PAGE.MenuAdmin
    }
]
